name: SAST Scan (Semgrep)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Semgrep
        run: pip install semgrep
      - name: Run Semgrep scan
        run: semgrep --config auto --json > semgrep-results.json
        continue-on-error: true
      - name: Upload Semgrep results
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-report
          path: semgrep-results.json
